ignoredBuiltDependencies:
  - lzma-native

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - active-win
  - electron
  - electron-winstaller
  - prisma
  - sharp
  - sqlite3
  - uiohook-napi
